#!/usr/bin/env python3
"""
Daily Content Scan
Combines Polymarket + Reddit into one alert
Run this daily for content ideas
"""

import json
from datetime import datetime
from pathlib import Path
from polymarket_scanner import find_holy_shit_content, generate_script_prompt
from reddit_scanner import scan_all as scan_reddit, generate_alert as reddit_alert

def run_daily_scan():
    """Run complete daily scan"""
    print("🐋 DAILY CONTENT SCAN")
    print("=" * 50)
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 50)
    
    output_dir = "output"
    Path(output_dir).mkdir(exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d')
    
    # Polymarket scan
    print("\n📊 POLYMARKET SCAN")
    print("-" * 30)
    poly_markets = find_holy_shit_content(limit=10)
    
    # Reddit scan
    print("\n📰 REDDIT SCAN")
    print("-" * 30)
    reddit_results = scan_reddit()
    
    # Combine into daily briefing
    briefing = f"""# 🐋 Daily Content Briefing
*{datetime.now().strftime('%Y-%m-%d %H:%M')}*

---

## 🔥 TOP POLYMARKET OPPORTUNITIES

"""
    
    for i, m in enumerate(poly_markets[:5], 1):
        briefing += f"### {i}. {m['question']}\n"
        if m['outcomes']:
            odds = " | ".join([f"**{o['name']}**: {o['probability']}%" for o in m['outcomes'][:2]])
            briefing += f"📊 {odds}\n\n"
        briefing += f"💰 Volume: ${m['volume']:,.0f}\n\n"
        if m['content_angles']:
            briefing += f"🎯 Angles: {', '.join(m['content_angles'])}\n\n"
        briefing += f"[View on Polymarket]({m['url']})\n\n"
        briefing += "---\n\n"
    
    briefing += """
## 📢 TOP REDDIT DISCUSSIONS

"""
    
    for i, post in enumerate(reddit_results.get('top_content', [])[:5], 1):
        briefing += f"### {i}. {post['title'][:80]}\n"
        briefing += f"📊 {post.get('score', 0)} upvotes | 💬 {post.get('num_comments', 0)} comments\n\n"
        briefing += f"📍 r/{post.get('subreddit', 'unknown')}\n\n"
        if post.get('content_angles'):
            briefing += f"🎯 {' '.join(post['content_angles'])}\n\n"
        briefing += f"[View Post]({post['url']})\n\n"
        briefing += "---\n\n"
    
    # Add script prompts
    briefing += """
## ✍️ READY-TO-USE SCRIPT PROMPTS

Copy these into ChatGPT to generate scripts:

"""
    
    for i, m in enumerate(poly_markets[:3], 1):
        briefing += f"### Script Prompt {i}: {m['question'][:50]}...\n\n"
        briefing += "```\n"
        briefing += generate_script_prompt(m)
        briefing += "\n```\n\n"
    
    # Action items
    briefing += """
---

## ✅ TODAY'S ACTION PLAN

1. [ ] Pick ONE topic from above
2. [ ] Paste script prompt into ChatGPT
3. [ ] Edit the script (add your spice)
4. [ ] Record with ElevenLabs voices
5. [ ] Edit in CapCut
6. [ ] Post to IG/TikTok/YT

**Time budget: 1 hour**

---
*Generated by Motion 🐋*
"""
    
    # Save briefing
    briefing_path = f"{output_dir}/daily_briefing_{timestamp}.md"
    with open(briefing_path, 'w') as f:
        f.write(briefing)
    
    # Save as latest
    with open(f"{output_dir}/TODAY.md", 'w') as f:
        f.write(briefing)
    
    print(f"\n✅ Daily briefing saved!")
    print(f"📁 {briefing_path}")
    print(f"📁 {output_dir}/TODAY.md")
    
    return briefing


if __name__ == '__main__':
    briefing = run_daily_scan()
    print("\n" + "=" * 50)
    print("📋 BRIEFING PREVIEW (first 2000 chars):")
    print("=" * 50)
    print(briefing[:2000])
